[[headers]]
  for = "/*" # you can configure the correct paths here
  [headers.values]
    access-control-allow-origin = "https://professorcarlos.blogspot.com" # see a list of allowed values here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin